[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture arm64",
  "apt-get update",
  "apt-get install -y --no-install-recommends libseccomp-dev:arm64"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
  "apt-get update",
  "apt-get install -y --no-install-recommends libseccomp-dev"
]
