[package]
name = "version-bump"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
cargo_metadata = "0.18"
clap = { version = "4.5", features = ["derive"] }
toml_edit = "0.22"
camino = "1.1"
