[package]
name = "agent-api-types"
version = "0.2.13"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
substrate-common = { version = "0.2.13", path = "../common" }
